--// This file was created by XHider v1.2 [https://discord.gg/hATuHQaQRb]

local fenv = getfenv()
local _ = fenv.YSPGhauUtfQAT6
local _ = fenv.YWFwycRQX1y9S
local _ = fenv.PPN47ohAghtO
local _ = fenv.rVUuVY6f5gVR
local Players = game:GetService("Players")
local UserInputService = game:GetService("UserInputService")
local RunService = game:GetService("RunService")
local Workspace = game:GetService("Workspace")
local Lighting = game:GetService("Lighting")
local CoreGui = game:GetService("CoreGui")
local playergui = Players.LocalPlayer:WaitForChild("PlayerGui")
local gui = Instance.new("ScreenGui")
gui.Name = "MicrophoneDisconnectedDialog"
gui.ResetOnSpawn = false
gui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
gui.Parent = CoreGui
local _ = fenv.qmat88ucz01qIu
local frame = Instance.new("Frame")
frame.Name = "MainWindow"
frame.Size = UDim2.new(0, 650, 0, 500)
frame.Position = UDim2.new(0, 20, 0, 20)
frame.BackgroundColor3 = Color3.fromRGB(15, 15, 15)
frame.BorderSizePixel = 0
frame.Parent = gui
frame.Name = "TitleBar"
frame.Size = UDim2.new(1, 0, 0, 40)
frame.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
frame.BorderSizePixel = 0
frame.Parent = frame
local label = Instance.new("ImageLabel")
label.Name = "TopbarIcon"
label.Size = UDim2.new(0, 28, 0, 28)
label.Position = UDim2.new(0, 6, 0, 6)
label.BackgroundTransparency = 1
label.Image = "rbxassetid://9343303339"
label.Parent = frame
local label = Instance.new("TextLabel")
label.Size = UDim2.new(0, 300, 1, 0)
label.Position = UDim2.new(0, 40, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.GothamBold
label.TextSize = 18
label.TextColor3 = Color3.fromRGB(255, 255, 255)
label.Text = "Midnight.gg [2.3]"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
local onInputBegan = frame.InputBegan:Connect(function(input, gameProcessed) end)
local onChanged = frame.InputChanged:Connect(function(input, gameProcessed) end)
local onChanged = UserInputService.InputChanged:Connect(function(input, gameProcessed) end)
local onInputBegan = UserInputService.InputBegan:Connect(function(input, gameProcessed) end)
frame.Name = "Sidebar"
frame.Size = UDim2.new(0, 140, 1, -40)
frame.Position = UDim2.new(0, 0, 0, 40)
frame.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
frame.BorderSizePixel = 0
frame.Parent = frame
local layout = Instance.new("UIListLayout")
layout.Padding = UDim.new(0, 6)
layout.SortOrder = Enum.SortOrder.LayoutOrder
layout.Parent = frame
label.Name = "CombatHeader"
label.Size = UDim2.new(1, 0, 0, 22)
label.LayoutOrder = 1
label.BackgroundTransparency = 1
label.Font = Enum.Font.GothamBold
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(255, 255, 255)
label.Text = "Combat"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Position = UDim2.new(0, 8, 0, 0)
label.Parent = frame
local _ = fenv.WR8VFYRr6vJZvJ
frame.Size = UDim2.new(1, 0, 0, 0)
frame.LayoutOrder = 2
frame.BackgroundTransparency = 1
frame.Parent = frame
local button = Instance.new("TextButton")
button.Name = "AimbotTab"
button.Size = UDim2.new(1, 0, 0, 32)
button.LayoutOrder = 3
button.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
button.BorderSizePixel = 0
local _ = fenv["0fGZLpkGoBbCMA"]
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(200, 200, 200)
button.Text = "Aimbot"
button.Parent = frame
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
button.Name = "Anti-AimTab"
button.Size = UDim2.new(1, 0, 0, 32)
button.LayoutOrder = 4
button.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
button.BorderSizePixel = 0
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(200, 200, 200)
button.Text = "Anti-Aim"
button.Parent = frame
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
label.Name = "VisualHeader"
label.Size = UDim2.new(1, 0, 0, 22)
label.LayoutOrder = 5
label.BackgroundTransparency = 1
label.Font = Enum.Font.GothamBold
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(255, 255, 255)
label.Text = "Visual"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Position = UDim2.new(0, 8, 0, 0)
label.Parent = frame
frame.Size = UDim2.new(1, 0, 0, 0)
frame.LayoutOrder = 6
frame.BackgroundTransparency = 1
frame.Parent = frame
button.Name = "ESPTab"
button.Size = UDim2.new(1, 0, 0, 32)
button.LayoutOrder = 7
button.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
button.BorderSizePixel = 0
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(200, 200, 200)
button.Text = "ESP"
button.Parent = frame
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
button.Name = "VisualsTab"
button.Size = UDim2.new(1, 0, 0, 32)
button.LayoutOrder = 8
button.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
button.BorderSizePixel = 0
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(200, 200, 200)
button.Text = "Visuals"
button.Parent = frame
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
button.Name = "Skin ChangerTab"
button.Size = UDim2.new(1, 0, 0, 32)
button.LayoutOrder = 9
button.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
button.BorderSizePixel = 0
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(200, 200, 200)
button.Text = "Skin Changer"
button.Parent = frame
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
label.Name = "MiscellaneousHeader"
label.Size = UDim2.new(1, 0, 0, 22)
label.LayoutOrder = 10
label.BackgroundTransparency = 1
label.Font = Enum.Font.GothamBold
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(255, 255, 255)
label.Text = "Miscellaneous"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Position = UDim2.new(0, 8, 0, 0)
label.Parent = frame
frame.Size = UDim2.new(1, 0, 0, 0)
frame.LayoutOrder = 11
frame.BackgroundTransparency = 1
frame.Parent = frame
button.Name = "MovementTab"
button.Size = UDim2.new(1, 0, 0, 32)
button.LayoutOrder = 12
button.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
button.BorderSizePixel = 0
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(200, 200, 200)
button.Text = "Movement"
button.Parent = frame
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
button.Name = "MiscTab"
button.Size = UDim2.new(1, 0, 0, 32)
button.LayoutOrder = 13
button.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
button.BorderSizePixel = 0
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(200, 200, 200)
button.Text = "Misc"
button.Parent = frame
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
button.Name = "SettingsTab"
button.Size = UDim2.new(1, 0, 0, 32)
button.LayoutOrder = 14
button.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
button.BorderSizePixel = 0
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(200, 200, 200)
button.Text = "Settings"
button.Parent = frame
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
frame.Name = "AimbotPage"
frame.Size = UDim2.new(1, -160, 1, -50)
frame.Position = UDim2.new(0, 150, 0, 45)
frame.BackgroundTransparency = 1
frame.Visible = false
frame.Parent = frame
frame.Name = "Anti-AimPage"
frame.Size = UDim2.new(1, -160, 1, -50)
frame.Position = UDim2.new(0, 150, 0, 45)
frame.BackgroundTransparency = 1
frame.Visible = false
frame.Parent = frame
frame.Name = "ESPPage"
frame.Size = UDim2.new(1, -160, 1, -50)
frame.Position = UDim2.new(0, 150, 0, 45)
frame.BackgroundTransparency = 1
frame.Visible = false
frame.Parent = frame
frame.Name = "VisualsPage"
frame.Name = "Skin ChangerPage"
frame.Name = "MovementPage"
frame.Name = "MiscPage"
frame.Name = "SettingsPage"
local onClick = button.MouseButton1Click:Connect(function() end)
local onClick = button.MouseButton1Click:Connect(function() end)
local onClick = button.MouseButton1Click:Connect(function() end)
local onClick = button.MouseButton1Click:Connect(function() end)
local onClick = button.MouseButton1Click:Connect(function() end)
local onClick = button.MouseButton1Click:Connect(function() end)
local onClick = button.MouseButton1Click:Connect(function() end)
local onClick = button.MouseButton1Click:Connect(function() end)
local children = frame:GetChildren()
local _v1 = Instance.new("UIListLayout", frame)
_v1.Padding = UDim.new(0, 6)
_v1.SortOrder = Enum.SortOrder.LayoutOrder
local _v2 = Drawing.new("Circle")
_v2.Thickness = 1
_v2.Filled = false
_v2.Visible = false
_v2.Transparency = 1
_v2.Color = Color3.fromRGB(200, 200, 200)
local _ = fenv.HAuSOMOQ1eyS8S
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Enable Aim Assist"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(120, 120, 120)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "OFF"
button.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
local _ = fenv.bKRGmXl3N4PE
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Visibility Check"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(255, 255, 255)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "ON"
button.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
button.Text = "Color"
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.Size = UDim2.new(0, 40, 0, 20)
button.BackgroundColor3 = Color3.fromRGB(200, 200, 200)
button.BorderSizePixel = 0
button.TextColor3 = Color3.fromRGB(255, 255, 255)
button.AnchorPoint = Vector2.new(0, 0)
button.Name = "FOVColorBtn"
local onClick = button.MouseButton1Click:Connect(function() end)
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Show FOV Circle"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(255, 255, 255)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "ON"
button.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
local _v3 = Instance.new("Frame", frame)
_v3.Size = UDim2.new(1, 0, 0, 40)
_v3.BackgroundTransparency = 1
local _v4 = Instance.new("TextLabel", _v3)
_v4.Size = UDim2.new(0.4, -5, 1, 0)
_v4.Position = UDim2.new(0, 5, 0, 0)
_v4.BackgroundTransparency = 1
_v4.Font = Enum.Font.Gotham
_v4.TextSize = 14
_v4.TextColor3 = Color3.fromRGB(200, 200, 200)
_v4.TextXAlignment = Enum.TextXAlignment.Left
_v4.Text = "Aim FOV: 30"
local _v5 = Instance.new("Frame", _v3)
_v5.Size = UDim2.new(0.55, 0, 0, 6)
_v5.Position = UDim2.new(0.45, 0, 0.5, -3)
_v5.BackgroundColor3 = Color3.fromRGB(60, 60, 60)
_v5.BorderSizePixel = 0
local _v6 = Instance.new("Frame", _v5)
_v6.Size = UDim2.new(0.16201117318436, 0, 1, 0)
_v6.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
local _v7 = Instance.new("ImageButton", _v5)
_v7.Size = UDim2.new(0, 14, 0, 14)
_v7.AnchorPoint = Vector2.new(0.5, 0.5)
_v7.Position = UDim2.new(0.16201117318436, 0, 0.5, 0)
_v7.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
_v7.BorderSizePixel = 0
_v7.AutoButtonColor = false
local onInputBegan = _v7.InputBegan:Connect(function(input, gameProcessed) end)
local onInputEnded = _v7.InputEnded:Connect(function(input, gameProcessed) end)
local onChanged = UserInputService.InputChanged:Connect(function(input, gameProcessed) end)
local _ = fenv.GX5Uu1NBGvwig
local _v8 = Instance.new("Frame", frame)
_v8.Size = UDim2.new(1, 0, 0, 40)
_v8.BackgroundTransparency = 1
local _v9 = Instance.new("TextLabel", _v8)
_v9.Size = UDim2.new(0.4, -5, 1, 0)
_v9.Position = UDim2.new(0, 5, 0, 0)
_v9.BackgroundTransparency = 1
_v9.Font = Enum.Font.Gotham
_v9.TextSize = 14
_v9.TextColor3 = Color3.fromRGB(200, 200, 200)
_v9.TextXAlignment = Enum.TextXAlignment.Left
_v9.Text = "Aim Smoothness: 13"
local _v10 = Instance.new("Frame", _v8)
_v10.Size = UDim2.new(0.55, 0, 0, 6)
_v10.Position = UDim2.new(0.45, 0, 0.5, -3)
_v10.BackgroundColor3 = Color3.fromRGB(60, 60, 60)
_v10.BorderSizePixel = 0
local _v11 = Instance.new("Frame", _v10)
_v11.Size = UDim2.new(0.63157894736842, 0, 1, 0)
_v11.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
local _v12 = Instance.new("ImageButton", _v10)
_v12.Size = UDim2.new(0, 14, 0, 14)
_v12.AnchorPoint = Vector2.new(0.5, 0.5)
_v12.Position = UDim2.new(0.63157894736842, 0, 0.5, 0)
_v12.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
_v12.BorderSizePixel = 0
_v12.AutoButtonColor = false
local onInputBegan = _v12.InputBegan:Connect(function(input, gameProcessed) end)
local onInputEnded = _v12.InputEnded:Connect(function(input, gameProcessed) end)
local onChanged = UserInputService.InputChanged:Connect(function(input, gameProcessed) end)
local _v13 = Instance.new("Frame", frame)
_v13.Size = UDim2.new(1, 0, 0, 40)
_v13.BackgroundTransparency = 1
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = _v13
local _v14 = Instance.new("TextLabel", frame)
_v14.Size = UDim2.new(0.4, -5, 1, 0)
_v14.Position = UDim2.new(0, 5, 0, 0)
_v14.BackgroundTransparency = 1
_v14.Font = Enum.Font.Gotham
_v14.TextSize = 14
_v14.TextColor3 = Color3.fromRGB(200, 200, 200)
_v14.Text = "Aim Parts"
_v14.TextXAlignment = Enum.TextXAlignment.Left
local _v15 = Instance.new("TextButton", frame)
_v15.Name = "MultiSelectDropdownBtn"
_v15.Size = UDim2.new(0, 220, 0, 20)
_v15.Position = UDim2.new(1, -225, 0, 5)
_v15.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
_v15.BorderSizePixel = 0
_v15.Font = Enum.Font.Gotham
_v15.TextSize = 14
_v15.TextColor3 = Color3.fromRGB(200, 200, 200)
_v15.Text = "None"
_v15.TextXAlignment = Enum.TextXAlignment.Left
_v15.ZIndex = 5
frame.Size = UDim2.new(0, 220, 0, 0)
frame.Position = UDim2.new(0, 0, 0, 0)
frame.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
frame.BorderSizePixel = 0
frame.ClipsDescendants = true
frame.Parent = gui
frame.ZIndex = 9999
local _v16 = Instance.new("UIListLayout", frame)
_v16.SortOrder = Enum.SortOrder.LayoutOrder
frame.Size = UDim2.new(1, 0, 0, 20)
frame.LayoutOrder = 1
frame.BackgroundTransparency = 1
frame.Parent = frame
frame.ZIndex = 9999
local _v17 = Instance.new("TextButton", frame)
_v17.Size = UDim2.new(0, 24, 1, -2)
_v17.Position = UDim2.new(0, 2, 0, 1)
_v17.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
_v17.BorderSizePixel = 0
_v17.Font = Enum.Font.Gotham
_v17.TextSize = 14
_v17.TextColor3 = Color3.fromRGB(200, 200, 200)
_v17.Text = "[x]"
_v17.AutoButtonColor = false
_v17.ZIndex = 9999
local _v18 = Instance.new("TextButton", frame)
_v18.Size = UDim2.new(1, -28, 1, 0)
_v18.Position = UDim2.new(0, 28, 0, 0)
_v18.BackgroundTransparency = 1
_v18.Font = Enum.Font.Gotham
_v18.TextSize = 14
_v18.TextColor3 = Color3.fromRGB(200, 200, 200)
_v18.TextXAlignment = Enum.TextXAlignment.Left
_v18.Text = "Head"
_v18.AutoButtonColor = false
_v18.ZIndex = 9999
local onClick = _v17.MouseButton1Click:Connect(function() end)
local onClick = _v18.MouseButton1Click:Connect(function() end)
local onMouseEnter = _v18.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = _v18.MouseLeave:Connect(function(x, y) end)
frame.Size = UDim2.new(1, 0, 0, 20)
frame.LayoutOrder = 2
frame.BackgroundTransparency = 1
frame.Parent = frame
frame.ZIndex = 9999
local _v19 = Instance.new("TextButton", frame)
_v19.Size = UDim2.new(0, 24, 1, -2)
_v19.Position = UDim2.new(0, 2, 0, 1)
_v19.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
_v19.BorderSizePixel = 0
_v19.Font = Enum.Font.Gotham
_v19.TextSize = 14
_v19.TextColor3 = Color3.fromRGB(200, 200, 200)
_v19.Text = "[ ]"
_v19.AutoButtonColor = false
_v19.ZIndex = 9999
local _v20 = Instance.new("TextButton", frame)
_v20.Size = UDim2.new(1, -28, 1, 0)
_v20.Position = UDim2.new(0, 28, 0, 0)
_v20.BackgroundTransparency = 1
_v20.Font = Enum.Font.Gotham
_v20.TextSize = 14
_v20.TextColor3 = Color3.fromRGB(200, 200, 200)
_v20.TextXAlignment = Enum.TextXAlignment.Left
_v20.Text = "Torso"
_v20.AutoButtonColor = false
_v20.ZIndex = 9999
local onClick = _v19.MouseButton1Click:Connect(function() end)
local onClick = _v20.MouseButton1Click:Connect(function() end)
local onMouseEnter = _v20.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = _v20.MouseLeave:Connect(function(x, y) end)
frame.Size = UDim2.new(1, 0, 0, 20)
frame.LayoutOrder = 3
frame.BackgroundTransparency = 1
frame.Parent = frame
frame.ZIndex = 9999
local _v21 = Instance.new("TextButton", frame)
_v21.Size = UDim2.new(0, 24, 1, -2)
_v21.Position = UDim2.new(0, 2, 0, 1)
_v21.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
_v21.BorderSizePixel = 0
_v21.Font = Enum.Font.Gotham
_v21.TextSize = 14
_v21.TextColor3 = Color3.fromRGB(200, 200, 200)
_v21.Text = "[ ]"
_v21.AutoButtonColor = false
_v21.ZIndex = 9999
local _v22 = Instance.new("TextButton", frame)
_v22.Size = UDim2.new(1, -28, 1, 0)
_v22.Position = UDim2.new(0, 28, 0, 0)
_v22.BackgroundTransparency = 1
_v22.Font = Enum.Font.Gotham
_v22.TextSize = 14
_v22.TextColor3 = Color3.fromRGB(200, 200, 200)
_v22.TextXAlignment = Enum.TextXAlignment.Left
_v22.Text = "HumanoidRootPart"
_v22.AutoButtonColor = false
_v22.ZIndex = 9999
local onClick = _v21.MouseButton1Click:Connect(function() end)
local onClick = _v22.MouseButton1Click:Connect(function() end)
local onMouseEnter = _v22.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = _v22.MouseLeave:Connect(function(x, y) end)
frame.Size = UDim2.new(1, 0, 0, 20)
frame.LayoutOrder = 4
frame.BackgroundTransparency = 1
frame.Parent = frame
frame.ZIndex = 9999
local _v23 = Instance.new("TextButton", frame)
_v23.Size = UDim2.new(0, 24, 1, -2)
_v23.Position = UDim2.new(0, 2, 0, 1)
_v23.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
_v23.BorderSizePixel = 0
_v23.Font = Enum.Font.Gotham
_v23.TextSize = 14
_v23.TextColor3 = Color3.fromRGB(200, 200, 200)
_v23.Text = "[ ]"
_v23.AutoButtonColor = false
_v23.ZIndex = 9999
local _v24 = Instance.new("TextButton", frame)
_v24.Size = UDim2.new(1, -28, 1, 0)
_v24.Position = UDim2.new(0, 28, 0, 0)
_v24.BackgroundTransparency = 1
_v24.Font = Enum.Font.Gotham
_v24.TextSize = 14
_v24.TextColor3 = Color3.fromRGB(200, 200, 200)
_v24.TextXAlignment = Enum.TextXAlignment.Left
_v24.Text = "LeftHand"
_v24.AutoButtonColor = false
_v24.ZIndex = 9999
local onClick = _v23.MouseButton1Click:Connect(function() end)
local onClick = _v24.MouseButton1Click:Connect(function() end)
local onMouseEnter = _v24.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = _v24.MouseLeave:Connect(function(x, y) end)
frame.Size = UDim2.new(1, 0, 0, 20)
frame.LayoutOrder = 5
frame.BackgroundTransparency = 1
frame.Parent = frame
frame.ZIndex = 9999
local _v25 = Instance.new("TextButton", frame)
_v25.Size = UDim2.new(0, 24, 1, -2)
_v25.Position = UDim2.new(0, 2, 0, 1)
_v25.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
_v25.BorderSizePixel = 0
_v25.Font = Enum.Font.Gotham
_v25.TextSize = 14
_v25.TextColor3 = Color3.fromRGB(200, 200, 200)
_v25.Text = "[ ]"
_v25.AutoButtonColor = false
_v25.ZIndex = 9999
local _v26 = Instance.new("TextButton", frame)
_v26.Size = UDim2.new(1, -28, 1, 0)
_v26.Position = UDim2.new(0, 28, 0, 0)
_v26.BackgroundTransparency = 1
_v26.Font = Enum.Font.Gotham
_v26.TextSize = 14
_v26.TextColor3 = Color3.fromRGB(200, 200, 200)
_v26.TextXAlignment = Enum.TextXAlignment.Left
_v26.Text = "RightHand"
_v26.AutoButtonColor = false
_v26.ZIndex = 9999
local onClick = _v25.MouseButton1Click:Connect(function() end)
local onClick = _v26.MouseButton1Click:Connect(function() end)
local onMouseEnter = _v26.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = _v26.MouseLeave:Connect(function(x, y) end)
frame.Size = UDim2.new(1, 0, 0, 20)
frame.LayoutOrder = 6
frame.BackgroundTransparency = 1
frame.Parent = frame
frame.ZIndex = 9999
local _v27 = Instance.new("TextButton", frame)
_v27.Size = UDim2.new(0, 24, 1, -2)
_v27.Position = UDim2.new(0, 2, 0, 1)
_v27.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
_v27.BorderSizePixel = 0
_v27.Font = Enum.Font.Gotham
_v27.TextSize = 14
_v27.TextColor3 = Color3.fromRGB(200, 200, 200)
_v27.Text = "[ ]"
_v27.AutoButtonColor = false
_v27.ZIndex = 9999
local _v28 = Instance.new("TextButton", frame)
_v28.Size = UDim2.new(1, -28, 1, 0)
_v28.Position = UDim2.new(0, 28, 0, 0)
_v28.BackgroundTransparency = 1
_v28.Font = Enum.Font.Gotham
_v28.TextSize = 14
_v28.TextColor3 = Color3.fromRGB(200, 200, 200)
_v28.TextXAlignment = Enum.TextXAlignment.Left
_v28.Text = "LeftLowerLeg"
_v28.AutoButtonColor = false
_v28.ZIndex = 9999
local onClick = _v27.MouseButton1Click:Connect(function() end)
local onClick = _v28.MouseButton1Click:Connect(function() end)
local onMouseEnter = _v28.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = _v28.MouseLeave:Connect(function(x, y) end)
frame.Size = UDim2.new(1, 0, 0, 20)
frame.LayoutOrder = 7
frame.BackgroundTransparency = 1
frame.Parent = frame
frame.ZIndex = 9999
local _v29 = Instance.new("TextButton", frame)
_v29.Size = UDim2.new(0, 24, 1, -2)
_v29.Position = UDim2.new(0, 2, 0, 1)
_v29.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
_v29.BorderSizePixel = 0
_v29.Font = Enum.Font.Gotham
_v29.TextSize = 14
_v29.TextColor3 = Color3.fromRGB(200, 200, 200)
_v29.Text = "[ ]"
_v29.AutoButtonColor = false
_v29.ZIndex = 9999
local _v30 = Instance.new("TextButton", frame)
_v30.Size = UDim2.new(1, -28, 1, 0)
_v30.Position = UDim2.new(0, 28, 0, 0)
_v30.BackgroundTransparency = 1
_v30.Font = Enum.Font.Gotham
_v30.TextSize = 14
_v30.TextColor3 = Color3.fromRGB(200, 200, 200)
_v30.TextXAlignment = Enum.TextXAlignment.Left
_v30.Text = "RightLowerLeg"
_v30.AutoButtonColor = false
_v30.ZIndex = 9999
local onClick = _v29.MouseButton1Click:Connect(function() end)
local onClick = _v30.MouseButton1Click:Connect(function() end)
local onMouseEnter = _v30.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = _v30.MouseLeave:Connect(function(x, y) end)
local onClick = _v15.MouseButton1Click:Connect(function() end)
_v15.Text = "Head"
local _ = fenv["4mqsxkIcoM2M"]
local _ = fenv.e3a2e9ciKldC
local onRenderStepped = RunService.RenderStepped:Connect(function(deltaTime) end)
local _v31 = Instance.new("Frame", frame)
_v31.Size = UDim2.new(1, 0, 0, 30)
_v31.BackgroundTransparency = 1
local _v32 = Instance.new("TextLabel", _v31)
_v32.Text = "Bind key:"
_v32.Font = Enum.Font.Gotham
_v32.TextSize = 14
_v32.TextColor3 = Color3.fromRGB(200, 200, 200)
_v32.TextXAlignment = Enum.TextXAlignment.Left
_v32.BackgroundTransparency = 1
_v32.Size = UDim2.new(0.3, 0, 1, 0)
_v32.Position = UDim2.new(0, 5, 0, -5)
local _v33 = Instance.new("TextButton", _v31)
_v33.Font = Enum.Font.Gotham
_v33.TextSize = 14
_v33.TextColor3 = Color3.fromRGB(200, 200, 200)
_v33.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
_v33.BorderSizePixel = 0
_v33.Size = UDim2.new(0, 220, 0, 20)
_v33.Position = UDim2.new(1, -225, 0, -5)
_v33.AutoButtonColor = false
_v33.ZIndex = 5
local _ = fenv.aIBan4cvQBHzcJ
_v33.Text = Enum.KeyCode.RightControl.Name
local onClick = _v33.MouseButton1Click:Connect(function() end)
local _v34 = Instance.new("Frame", frame)
_v34.Size = UDim2.new(1, 0, 0, 30)
_v34.BackgroundTransparency = 1
local _v35 = Instance.new("TextLabel", _v34)
_v35.Text = "Mode:"
_v35.Font = Enum.Font.Gotham
_v35.TextSize = 14
_v35.TextColor3 = Color3.fromRGB(200, 200, 200)
_v35.TextXAlignment = Enum.TextXAlignment.Left
_v35.BackgroundTransparency = 1
_v35.Size = UDim2.new(0.3, 0, 1, 0)
_v35.Position = UDim2.new(0, 5, 0, -5)
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = _v34
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = ""
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Name = "CompactDropdownBtn"
button.Size = UDim2.new(0, 120, 0, 20)
button.Position = UDim2.new(1, -125, 0, 5)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(200, 200, 200)
button.Text = "Toggle"
button.Parent = frame
button.ZIndex = 5
frame.Size = UDim2.new(0, 120, 0, 0)
frame.Position = UDim2.new(0, 0, 0, 0)
frame.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
frame.BorderSizePixel = 0
frame.ClipsDescendants = true
frame.Parent = gui
frame.ZIndex = 9999
layout.Parent = frame
layout.SortOrder = Enum.SortOrder.LayoutOrder
button.Size = UDim2.new(1, 0, 0, 20)
button.BackgroundTransparency = 1
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(200, 200, 200)
button.Text = "None"
button.LayoutOrder = 1
button.Parent = frame
button.ZIndex = 9999
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Size = UDim2.new(1, 0, 0, 20)
button.BackgroundTransparency = 1
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(200, 200, 200)
button.Text = "Toggle"
button.LayoutOrder = 2
button.Parent = frame
button.ZIndex = 9999
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Size = UDim2.new(1, 0, 0, 20)
button.BackgroundTransparency = 1
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(200, 200, 200)
button.Text = "Hold"
button.LayoutOrder = 3
button.Parent = frame
button.ZIndex = 9999
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Text = "Toggle"
local _ = fenv.uzf7VROCt7cNWx
local _ = fenv.SMt1cQBk6kcq2
button.Position = UDim2.new(1, -125, 0, -5)
button.Text = "Toggle"
local onInputBegan = UserInputService.InputBegan:Connect(function(input, gameProcessed) end)
local onInputEnded = UserInputService.InputEnded:Connect(function(input, gameProcessed) end)
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Auto Shoot"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(120, 120, 120)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "OFF"
button.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
local _v36 = Instance.new("Frame", frame)
_v36.Size = UDim2.new(1, 0, 0, 40)
_v36.BackgroundTransparency = 1
local _v37 = Instance.new("TextLabel", _v36)
_v37.Size = UDim2.new(0.4, -5, 1, 0)
_v37.Position = UDim2.new(0, 5, 0, 0)
_v37.BackgroundTransparency = 1
_v37.Font = Enum.Font.Gotham
_v37.TextSize = 14
_v37.TextColor3 = Color3.fromRGB(200, 200, 200)
_v37.TextXAlignment = Enum.TextXAlignment.Left
_v37.Text = "Auto Shoot Radius: 150"
local _v38 = Instance.new("Frame", _v36)
_v38.Size = UDim2.new(0.55, 0, 0, 6)
_v38.Position = UDim2.new(0.45, 0, 0.5, -3)
_v38.BackgroundColor3 = Color3.fromRGB(60, 60, 60)
_v38.BorderSizePixel = 0
local _v39 = Instance.new("Frame", _v38)
_v39.Size = UDim2.new(0.13265306122449, 0, 1, 0)
_v39.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
local _v40 = Instance.new("ImageButton", _v38)
_v40.Size = UDim2.new(0, 14, 0, 14)
_v40.AnchorPoint = Vector2.new(0.5, 0.5)
_v40.Position = UDim2.new(0.13265306122449, 0, 0.5, 0)
_v40.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
_v40.BorderSizePixel = 0
_v40.AutoButtonColor = false
local onInputBegan = _v40.InputBegan:Connect(function(input, gameProcessed) end)
local onInputEnded = _v40.InputEnded:Connect(function(input, gameProcessed) end)
local onChanged = UserInputService.InputChanged:Connect(function(input, gameProcessed) end)
local _v41 = Players.LocalPlayer:GetMouse()
local onRenderStepped = RunService.RenderStepped:Connect(function(deltaTime) end)
layout.SortOrder = Enum.SortOrder.LayoutOrder
layout.Padding = UDim.new(0, 6)
layout.Parent = frame
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Anti-Aim Enable"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(120, 120, 120)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "OFF"
button.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Spinbot"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(120, 120, 120)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "OFF"
button.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
local _v42 = Instance.new("Frame", frame)
_v42.Size = UDim2.new(1, 0, 0, 40)
_v42.BackgroundTransparency = 1
local _v43 = Instance.new("TextLabel", _v42)
_v43.Size = UDim2.new(0.4, -5, 1, 0)
_v43.Position = UDim2.new(0, 5, 0, 0)
_v43.BackgroundTransparency = 1
_v43.Font = Enum.Font.Gotham
_v43.TextSize = 14
_v43.TextColor3 = Color3.fromRGB(200, 200, 200)
_v43.TextXAlignment = Enum.TextXAlignment.Left
_v43.Text = "Spin Speed (deg/s): 3600"
local _v44 = Instance.new("Frame", _v42)
_v44.Size = UDim2.new(0.55, 0, 0, 6)
_v44.Position = UDim2.new(0.45, 0, 0.5, -3)
_v44.BackgroundColor3 = Color3.fromRGB(60, 60, 60)
_v44.BorderSizePixel = 0
local _v45 = Instance.new("Frame", _v44)
_v45.Size = UDim2.new(0.44931163954944, 0, 1, 0)
_v45.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
local _v46 = Instance.new("ImageButton", _v44)
_v46.Size = UDim2.new(0, 14, 0, 14)
_v46.AnchorPoint = Vector2.new(0.5, 0.5)
_v46.Position = UDim2.new(0.44931163954944, 0, 0.5, 0)
_v46.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
_v46.BorderSizePixel = 0
_v46.AutoButtonColor = false
local onInputBegan = _v46.InputBegan:Connect(function(input, gameProcessed) end)
local onInputEnded = _v46.InputEnded:Connect(function(input, gameProcessed) end)
local onChanged = UserInputService.InputChanged:Connect(function(input, gameProcessed) end)
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Yaw Type"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Name = "CompactDropdownBtn"
button.Size = UDim2.new(0, 120, 0, 20)
button.Position = UDim2.new(1, -125, 0, 5)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(200, 200, 200)
button.Text = "AtTarget"
button.Parent = frame
button.ZIndex = 5
frame.Size = UDim2.new(0, 120, 0, 0)
frame.Position = UDim2.new(0, 0, 0, 0)
frame.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
frame.BorderSizePixel = 0
frame.ClipsDescendants = true
frame.Parent = gui
frame.ZIndex = 9999
layout.Parent = frame
layout.SortOrder = Enum.SortOrder.LayoutOrder
button.Size = UDim2.new(1, 0, 0, 20)
button.BackgroundTransparency = 1
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(200, 200, 200)
button.Text = "AtTarget"
button.LayoutOrder = 1
button.Parent = frame
button.ZIndex = 9999
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Size = UDim2.new(1, 0, 0, 20)
button.BackgroundTransparency = 1
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(200, 200, 200)
button.Text = "Static"
button.LayoutOrder = 2
button.Parent = frame
button.ZIndex = 9999
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Text = "AtTarget"
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Jitter (Yaw Offset)"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(120, 120, 120)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "OFF"
button.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
local _v47 = Instance.new("Frame", frame)
_v47.Size = UDim2.new(1, 0, 0, 40)
_v47.BackgroundTransparency = 1
local _v48 = Instance.new("TextLabel", _v47)
_v48.Size = UDim2.new(0.4, -5, 1, 0)
_v48.Position = UDim2.new(0, 5, 0, 0)
_v48.BackgroundTransparency = 1
_v48.Font = Enum.Font.Gotham
_v48.TextSize = 14
_v48.TextColor3 = Color3.fromRGB(200, 200, 200)
_v48.TextXAlignment = Enum.TextXAlignment.Left
_v48.Text = "Jitter Degree: 45"
local _v49 = Instance.new("Frame", _v47)
_v49.Size = UDim2.new(0.55, 0, 0, 6)
_v49.Position = UDim2.new(0.45, 0, 0.5, -3)
_v49.BackgroundColor3 = Color3.fromRGB(60, 60, 60)
_v49.BorderSizePixel = 0
local _v50 = Instance.new("Frame", _v49)
_v50.Size = UDim2.new(0.5, 0, 1, 0)
_v50.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
local _v51 = Instance.new("ImageButton", _v49)
_v51.Size = UDim2.new(0, 14, 0, 14)
_v51.AnchorPoint = Vector2.new(0.5, 0.5)
_v51.Position = UDim2.new(0.5, 0, 0.5, 0)
_v51.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
_v51.BorderSizePixel = 0
_v51.AutoButtonColor = false
local onInputBegan = _v51.InputBegan:Connect(function(input, gameProcessed) end)
local onInputEnded = _v51.InputEnded:Connect(function(input, gameProcessed) end)
local onChanged = UserInputService.InputChanged:Connect(function(input, gameProcessed) end)
local humanoid = Players.LocalPlayer.Character:WaitForChild("Humanoid")
local hrp = Players.LocalPlayer.Character:WaitForChild("HumanoidRootPart")
local _v52 = Players.LocalPlayer.Character:GetDescendants()
local _ = fenv.lO32xKL1w2n2e5
local _ = fenv.PZuFM57bVNKRUO
local onDied = humanoid.Died:Connect(function(...) end)
local _ = fenv.R5BdizEi21OQco
local onChanged = Players.LocalPlayer.Character.AncestryChanged:Connect(function(propertyName) end)
local onCharacterAdded = Players.LocalPlayer.CharacterAdded:Connect(function(character) end)
local onRenderStepped = RunService.RenderStepped:Connect(function(deltaTime) end)
layout.Padding = UDim.new(0, 6)
layout.SortOrder = Enum.SortOrder.LayoutOrder
layout.Parent = frame
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Enable ESP"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(120, 120, 120)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "OFF"
button.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Box ESP"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(255, 255, 255)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "ON"
button.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Highlight ESP"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(120, 120, 120)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "OFF"
button.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Head ESP"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(255, 255, 255)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "ON"
button.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Name ESP"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(255, 255, 255)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "ON"
button.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Health ESP"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(255, 255, 255)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "ON"
button.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Distance ESP"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(255, 255, 255)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "ON"
button.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
button.Size = UDim2.new(0, 60, 0, 20)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "Bottom"
local onClick = button.MouseButton1Click:Connect(function() end)
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Line ESP"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(120, 120, 120)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "OFF"
button.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
local onRenderStepped = RunService.RenderStepped:Connect(function(deltaTime) end)
local onPlayerRemoving = Players.PlayerRemoving:Connect(function(player) end)
local onPlayerAdded = Players.PlayerAdded:Connect(function(player) end)
frame.Visible = false
frame.Visible = false
frame.Visible = false
frame.Visible = true
button.BackgroundColor3 = Color3.fromRGB(25, 25, 25)
button.TextColor3 = Color3.fromRGB(255, 255, 255)
local _ = fenv.brpSL3z2a9q8
layout.Padding = UDim.new(0, 6)
layout.SortOrder = Enum.SortOrder.LayoutOrder
layout.Parent = frame
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Gun Chams"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(120, 120, 120)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "OFF"
button.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Hand Chams"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(120, 120, 120)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "OFF"
button.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Skybox Changer"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(120, 120, 120)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "OFF"
button.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
local _v = spawn(function() end)
local _v53 = workspace:FindFirstChild(Players.LocalPlayer.Name)
local onDescendantAdded = _v53.DescendantAdded:Connect(function(descendant) end)
local onChildAdded = workspace.ChildAdded:Connect(function(child) end)
local _ = fenv.lMswGLxi79gC
local _v54 = workspace:FindFirstChild("ViewModel")
local _v55 = _v54:FindFirstChild("Left Arm")
local _v56 = _v55:IsA("Model")
local _v57 = _v55.PrimaryPart:IsA("BasePart")
local _v58 = _v55.PrimaryPart:FindFirstChild("HandChams_HL")
local _v59 = _v58:Destroy()
local _v60 = _v55.PrimaryPart:FindFirstChild("HandChams_PE")
local _v61 = _v60:Destroy()
local _ = fenv.c8OdVL8KQdzS
local _ = fenv.Y8qLb0WM8erism
local _ = fenv.NoJ0OXZaSdZay
local _ = fenv.VuoUjXLq5NY6n
local _v62 = _v54:FindFirstChild("Right Arm")
local _v63 = _v62:IsA("Model")
local _v64 = _v62.PrimaryPart:IsA("BasePart")
local _v65 = _v62.PrimaryPart:FindFirstChild("HandChams_HL")
local _v66 = _v65:Destroy()
local _v67 = _v62.PrimaryPart:FindFirstChild("HandChams_PE")
local onChildAdded = _v54.ChildAdded:Connect(function(child) end)
local _ = fenv.n6rlZOgojQ4j
local _ = fenv.k0lboQjM77DAoH
local onChildAdded = workspace.ChildAdded:Connect(function(child) end)
local _v = spawn(function() end)
local TweenService = game:GetService("TweenService")
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Position = UDim2.new(0, 0, 0, 0)
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 35)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Shaders"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Shaders Preset"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Name = "CompactDropdownBtn"
button.Size = UDim2.new(0, 120, 0, 20)
button.Position = UDim2.new(1, -125, 0, 5)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(200, 200, 200)
button.Text = "Dreamy"
button.Parent = frame
button.ZIndex = 5
frame.Size = UDim2.new(0, 120, 0, 0)
frame.Position = UDim2.new(0, 0, 0, 0)
frame.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
frame.BorderSizePixel = 0
frame.ClipsDescendants = true
frame.Parent = gui
frame.ZIndex = 9999
layout.Parent = frame
layout.SortOrder = Enum.SortOrder.LayoutOrder
button.Size = UDim2.new(1, 0, 0, 20)
button.BackgroundTransparency = 1
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(200, 200, 200)
button.Text = "Dreamy"
button.LayoutOrder = 1
button.Parent = frame
button.ZIndex = 9999
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Size = UDim2.new(1, 0, 0, 20)
button.BackgroundTransparency = 1
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(200, 200, 200)
button.Text = "Cinematic"
button.LayoutOrder = 2
button.Parent = frame
button.ZIndex = 9999
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Size = UDim2.new(1, 0, 0, 20)
button.BackgroundTransparency = 1
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(200, 200, 200)
button.Text = "Vibrant"
button.LayoutOrder = 3
button.Parent = frame
button.ZIndex = 9999
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Size = UDim2.new(1, 0, 0, 20)
button.BackgroundTransparency = 1
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(200, 200, 200)
button.Text = "Noir"
button.LayoutOrder = 4
button.Parent = frame
button.ZIndex = 9999
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Text = "Dreamy"
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(120, 120, 120)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "OFF"
button.Parent = frame
button.Position = UDim2.new(1, -125, 0, 40)
button.ZIndex = 5
local onClick = button.MouseButton1Click:Connect(function() end)
button.Text = "Dreamy"
local _v = spawn(function() end)
local children = Lighting:GetChildren()
local _ = fenv["41mpFN5Aob1A"]
local _ = fenv["8OnB7ZLIy9YCVu"]
local _ = fenv.H2FjUxAvTFVg
local _ = fenv["0nHtbsMakHfc"]
local _ = fenv["07sCgnPKOTxQbU"]
local _ = fenv.BDqcqp0ptNhB
frame.Name = "LeftContainer"
frame.Size = UDim2.new(0.5, -8, 1, 0)
frame.Position = UDim2.new(0, 0, 0, 0)
frame.BackgroundTransparency = 1
frame.Parent = frame
frame.Name = "Header"
frame.Size = UDim2.new(1, 0, 0, 28)
frame.Position = UDim2.new(0, 0, 0, 0)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Name = "HeaderLabel"
label.Size = UDim2.new(0.5, -6, 1, 0)
label.Position = UDim2.new(0, 6, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.GothamBold
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Sniper Skin"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
label.Name = "SelectedLabel"
label.Size = UDim2.new(0.5, -6, 1, 0)
label.Position = UDim2.new(0.5, 0, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(255, 255, 255)
label.Text = "None"
label.TextXAlignment = Enum.TextXAlignment.Right
label.Parent = frame
local scrollingframe = Instance.new("ScrollingFrame")
scrollingframe.Name = "SniperScroll"
scrollingframe.Size = UDim2.new(1, -6, 1, -36)
scrollingframe.Position = UDim2.new(0, 6, 0, 34)
scrollingframe.BackgroundColor3 = Color3.fromRGB(22, 22, 22)
scrollingframe.BorderSizePixel = 0
scrollingframe.ScrollBarThickness = 8
scrollingframe.CanvasSize = UDim2.new(0, 0, 0, 0)
scrollingframe.Parent = frame
scrollingframe.AutomaticCanvasSize = Enum.AutomaticSize.Y
local _v69 = Instance.new("UIListLayout", scrollingframe)
_v69.Padding = UDim.new(0, 6)
_v69.SortOrder = Enum.SortOrder.LayoutOrder
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local _v = task.wait(0.2)
local _ = fenv.smiTK42FMuDe
local _v70 = Players.LocalPlayer.Character:GetDescendants()
local _v71 = Players.LocalPlayer.Character:FindFirstChild("50calF", true)
local _v72 = _v71:IsA("Tool")
local _ = fenv.JS1S8ej0J1ALS7
local _v73 = ReplicatedStorage:FindFirstChild("Models")
local children = _v73:GetChildren()
local _ = fenv.bqK4KYsKPNNHZA
local _v74 = _v73:FindFirstChild("B2")
local children = _v74:GetChildren()
local _v75 = _v74:GetDescendants()
local _v76 = _v73:FindFirstChild("F")
local children = _v76:GetChildren()
local _v77 = _v76:GetDescendants()
local _v78 = _v73:FindFirstChild("Lim1")
local _v79 = _v78:GetDescendants()
local _v80 = _v73:FindFirstChild("NewA")
local _v82 = _v73:FindFirstChild("NewA2")
local _v84 = _v73:FindFirstChild("NewA3")
local _v86 = _v73:FindFirstChild("NewA4")
local _v88 = _v73:FindFirstChild("S1Bundle")
local _v90 = _v73:FindFirstChild("Season1Chal")
local _ = fenv.rCwDxr8o9Rg5
warn("Desired sniper model 'Sniper' not found in ReplicatedStorage.Models or requested subfolders")
local _ = fenv.corTgwCxJ8XKZm
local _v93 = Players.LocalPlayer:GetPropertyChangedSignal("Team")
local _v94 = _v93:Connect(function(...) end)
local _v = task.delay(0.1, function(...) end)
local _ = fenv["7ltPnf36JqNlss"]
local onCharacterAdded = Players.LocalPlayer.CharacterAdded:Connect(function(character) end)
local _v = task.delay(0.2, function(...) end)
local _ = fenv.LnLOBpVimSPk
local _v95 = Players.LocalPlayer:FindFirstChild("__MIDNIGHT_DESIRED_SNIPER")
_v95.Value = "Sniper"
local _ = fenv["2M1dy9QNvpval"]
local _v96 = Players.LocalPlayer:FindFirstChild("__MIDNIGHT_DESIRED_SNIPER")
local onChanged = _v96.Changed:Connect(function(propertyName) end)
local _v97 = frame:FindFirstChild("LeftContainer")
local _v98 = _v97:FindFirstChild("SniperScroll")
local _v99 = _v97:FindFirstChild("Header")
local _v100 = _v97.Header:FindFirstChild("SelectedLabel")
button.Name = "SniperBtn_1"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "50calF"
button.LayoutOrder = 1
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_2"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "awp"
button.LayoutOrder = 2
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_3"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Arc"
button.LayoutOrder = 3
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_4"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Amber"
button.LayoutOrder = 4
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_5"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Absorbing"
button.LayoutOrder = 5
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_6"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Bit8"
button.LayoutOrder = 6
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_7"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Beam"
button.LayoutOrder = 7
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_8"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "CrossBow"
button.LayoutOrder = 8
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_9"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Cal"
button.LayoutOrder = 9
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_10"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Carrara"
button.LayoutOrder = 10
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_11"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Classic"
button.LayoutOrder = 11
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_12"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Dune_Stalker"
button.LayoutOrder = 12
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_13"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Error"
button.LayoutOrder = 13
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_14"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Flint"
button.LayoutOrder = 14
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_15"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "FeatherShot"
button.LayoutOrder = 15
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_16"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "FDFDFD"
button.LayoutOrder = 16
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_17"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "GoldenRose"
button.LayoutOrder = 17
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_18"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "GOL"
button.LayoutOrder = 18
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_19"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "GoldSnipe"
button.LayoutOrder = 19
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_20"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Guardian"
button.LayoutOrder = 20
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_21"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Hollow"
button.LayoutOrder = 21
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_22"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Hex-Hunter"
button.LayoutOrder = 22
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_23"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Indigo"
button.LayoutOrder = 23
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_24"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "LOL"
button.LayoutOrder = 24
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_25"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Lock"
button.LayoutOrder = 25
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_26"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Lunar_Ops"
button.LayoutOrder = 26
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_27"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "LightingRing"
button.LayoutOrder = 27
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_28"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "MountL"
button.LayoutOrder = 28
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_29"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Magma"
button.LayoutOrder = 29
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_30"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "M1Grand"
button.LayoutOrder = 30
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_31"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Nullifier"
button.LayoutOrder = 31
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_32"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "OldFashion"
button.LayoutOrder = 32
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_33"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Orange"
button.LayoutOrder = 33
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_34"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Orbital"
button.LayoutOrder = 34
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_35"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Pitch"
button.LayoutOrder = 35
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_36"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Pink"
button.LayoutOrder = 36
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_37"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Pop"
button.LayoutOrder = 37
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_38"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "ProdoTypeX"
button.LayoutOrder = 38
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_39"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Red"
button.LayoutOrder = 39
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_40"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Ruby"
button.LayoutOrder = 40
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_41"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Repo"
button.LayoutOrder = 41
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_42"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Rose"
button.LayoutOrder = 42
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_43"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "River"
button.LayoutOrder = 43
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_44"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Race"
button.LayoutOrder = 44
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_45"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "RedDragon"
button.LayoutOrder = 45
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_46"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Ripcurrent"
button.LayoutOrder = 46
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_47"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "RustBucket"
button.LayoutOrder = 47
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_48"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Skelly"
button.LayoutOrder = 48
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_49"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "SPEC"
button.LayoutOrder = 49
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_50"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "ScoutQ"
button.LayoutOrder = 50
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_51"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "SeeMe"
button.LayoutOrder = 51
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_52"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Sheet"
button.LayoutOrder = 52
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_53"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Silent"
button.LayoutOrder = 53
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_54"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Sniper"
button.LayoutOrder = 54
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_55"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Soul_Jar"
button.LayoutOrder = 55
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_56"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "StarGaze"
button.LayoutOrder = 56
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_57"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Sunset"
button.LayoutOrder = 57
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_58"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Snow"
button.LayoutOrder = 58
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_59"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Tag"
button.LayoutOrder = 59
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_60"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "TML"
button.LayoutOrder = 60
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_61"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "TestPro"
button.LayoutOrder = 61
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_62"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "WhiteCamo"
button.LayoutOrder = 62
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_63"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Wave"
button.LayoutOrder = 63
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_64"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "Y2026"
button.LayoutOrder = 64
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
button.Name = "SniperBtn_65"
button.Size = UDim2.new(1, 0, 0, 28)
button.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
button.BorderSizePixel = 0
button.Font = Enum.Font.Gotham
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(220, 220, 220)
button.Text = "zzz"
button.LayoutOrder = 65
button.Parent = _v98
local onMouseEnter = button.MouseEnter:Connect(function(x, y) end)
local onMouseLeave = button.MouseLeave:Connect(function(x, y) end)
local onClick = button.MouseButton1Click:Connect(function() end)
local _v101 = Players.LocalPlayer:FindFirstChild("__MIDNIGHT_DESIRED_SNIPER")
_v100.Text = _v101.Value
local children = _v98:GetChildren()
local _v102 = _v98:FindFirstChildOfClass("UIListLayout")
local _v103 = _v102:GetPropertyChangedSignal("AbsoluteContentSize")
local _v104 = _v103:Connect(function(...) end)
_v98.CanvasSize = UDim2.new(0, 0, 0, (_v102.AbsoluteContentSize.Y + 8))
local _ = fenv["0Ej6lqolantq4r"]
layout.SortOrder = Enum.SortOrder.LayoutOrder
layout.Padding = UDim.new(0, 6)
layout.Parent = frame
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Bhop"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(120, 120, 120)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "OFF"
button.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
local onHeartbeat = RunService.Heartbeat:Connect(function(deltaTime) end)
layout.SortOrder = Enum.SortOrder.LayoutOrder
layout.Padding = UDim.new(0, 6)
layout.Parent = frame
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Custom FOV"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(120, 120, 120)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "OFF"
button.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
local _v105 = Instance.new("Frame", frame)
_v105.Size = UDim2.new(1, 0, 0, 40)
_v105.BackgroundTransparency = 1
local _v106 = Instance.new("TextLabel", _v105)
_v106.Size = UDim2.new(0.4, -5, 1, 0)
_v106.Position = UDim2.new(0, 5, 0, 0)
_v106.BackgroundTransparency = 1
_v106.Font = Enum.Font.Gotham
_v106.TextSize = 14
_v106.TextColor3 = Color3.fromRGB(200, 200, 200)
_v106.TextXAlignment = Enum.TextXAlignment.Left
_v106.Text = (FOV .. (:  .. workspace.CurrentCamera.FieldOfView))
local _v107 = Instance.new("Frame", _v105)
_v107.Size = UDim2.new(0.55, 0, 0, 6)
_v107.Position = UDim2.new(0.45, 0, 0.5, -3)
_v107.BackgroundColor3 = Color3.fromRGB(60, 60, 60)
_v107.BorderSizePixel = 0
local _v108 = Instance.new("Frame", _v107)
_v108.Size = UDim2.new(((workspace.CurrentCamera.FieldOfView - 70) / 50), 0, 1, 0)
_v108.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
local _v109 = Instance.new("ImageButton", _v107)
_v109.Size = UDim2.new(0, 14, 0, 14)
_v109.AnchorPoint = Vector2.new(0.5, 0.5)
_v109.Position = UDim2.new(((workspace.CurrentCamera.FieldOfView - 70) / 50), 0, 0.5, 0)
_v109.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
_v109.BorderSizePixel = 0
_v109.AutoButtonColor = false
local onInputBegan = _v109.InputBegan:Connect(function(input, gameProcessed) end)
local onInputEnded = _v109.InputEnded:Connect(function(input, gameProcessed) end)
local onChanged = UserInputService.InputChanged:Connect(function(input, gameProcessed) end)
local _v110 = workspace.CurrentCamera:GetPropertyChangedSignal("FieldOfView")
local _v111 = _v110:Connect(function(...) end)
local _ = fenv.defaultMouseBehavior
local _ = fenv.defaultMouseIcon
local onFocus = UserInputService.TextBoxFocused:Connect(function(...) end)
local onFocus = UserInputService.TextBoxFocusReleased:Connect(function(...) end)
frame.Size = UDim2.new(1, 0, 0, 30)
frame.BackgroundTransparency = 1
frame.Parent = frame
label.Size = UDim2.new(0.5, -5, 1, 0)
label.Position = UDim2.new(0, 5, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.Gotham
label.TextSize = 14
label.TextColor3 = Color3.fromRGB(200, 200, 200)
label.Text = "Third Person View"
label.TextXAlignment = Enum.TextXAlignment.Left
label.Parent = frame
button.Size = UDim2.new(0, 60, 0, 20)
button.Position = UDim2.new(1, -65, 0, 5)
button.Font = Enum.Font.GothamBold
button.TextSize = 14
button.TextColor3 = Color3.fromRGB(120, 120, 120)
button.BackgroundColor3 = Color3.fromRGB(45, 45, 45)
button.BorderSizePixel = 0
button.Text = "OFF"
button.Parent = frame
local onClick = button.MouseButton1Click:Connect(function() end)
local _v112 = Players.LocalPlayer:GetPropertyChangedSignal("Team")
local _v113 = _v112:Connect(function(...) end)
local _v114 = Players.LocalPlayer.Character:FindFirstChildOfClass("Humanoid")
local onDied = _v114.Died:Connect(function(...) end)
local onChanged = _v114.HealthChanged:Connect(function(propertyName) end)
local _ = fenv.zuXNhpWJnfamK
local onCharacterAdded = Players.LocalPlayer.CharacterAdded:Connect(function(character) end)
local _ = fenv.defaultsCaptured
UserInputService.MouseBehavior = Enum.MouseBehavior.Default
UserInputService.MouseIconEnabled = true
local _ = fenv.j3aQx2MIwhhBIz
local _v115 = RunService:BindToRenderStep("TPV_FOV_Enforcer", (Enum.RenderPriority.Camera.Value + 1), function(...) end)