--// This file was created by XHider v1.2 [https://discord.gg/hATuHQaQRb]

local fenv = getfenv()
local _ = fenv.FRsHokT5dJzDu
local _ = fenv["8DoY00JRD8RdV"]
local _ = fenv.SeiWnqw1Imx8
local _ = fenv.sHuNWZapcEXbA
print("!! [DETECTION] : Executor Global Found: getgenv")
local _ = fenv.gDoF7yXM44eL4
print("!! [DETECTION] : Executor Global Found: getrenv")
print("!! [DETECTION] : Executor Global Found: getreg")
print("!! [DETECTION] : Executor Global Found: getrenv")
local _ = fenv.getinstancelist
local _ = _G.getinstancelist
print("!! [DETECTION] : Executor Global Found: getnilinstances")
print("!! [DETECTION] : Executor Global Found: getgc")
print("!! [DETECTION] : Executor Global Found: getconnections")
print("!! [DETECTION] : Executor Global Found: getloadedmodules")
print("!! [DETECTION] : Executor Global Found: hookfunction")
print("!! [DETECTION] : Executor Global Found: hookmetamethod")
print("!! [DETECTION] : Executor Global Found: replaceclosure")
print("!! [DETECTION] : Executor Global Found: checkclosure")
print("!! [DETECTION] : Executor Global Found: newcclosure")
print("!! [DETECTION] : Executor Global Found: loadstring")
print("!! [DETECTION] : Executor Global Found: getrawmetatable")
print("!! [DETECTION] : Executor Global Found: setrawmetatable")
print("!! [DETECTION] : Executor Global Found: setreadonly")
local _ = fenv.make_writeable
local _ = _G.make_writeable
print("!! [DETECTION] : Executor Global Found: isreadonly")
local _ = fenv.is_lclosure
local _ = _G.is_lclosure
print("!! [DETECTION] : Executor Global Found: isexecutorclosure")
print("!! [DETECTION] : Executor Global Found: identifyexecutor")
print("!! [DETECTION] : Executor Global Found: getexecutorname")
local _ = fenv.rawget
local _ = fenv.XuBYKwoMGy6m6
print("!! [DETECTION] : FUNCTION HOOKED: xpcall (Source: [C])")
print("!! [DETECTION] : FUNCTION HOOKED: warn (Source: C:\\Users\\Administrator\\Documents\\nunu\\uveilr\\flow\\sandbox)")
print("!! [DETECTION] : FUNCTION HOOKED: rawset (Source: C:\\Users\\Administrator\\Documents\\nunu\\uveilr\\flow\\sandbox)")
print("!! [DETECTION] : FUNCTION HOOKED: print (Source: C:\\Users\\Administrator\\Documents\\nunu\\uveilr\\flow\\sandbox)")
print("!! [DETECTION] : FUNCTION HOOKED: debug.info (Source: [C])")
print("!! [DETECTION] : FUNCTION HOOKED: game.HttpGet (Source: [string \"C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\tmp-8148-P6dUmAfzPA4T-.lua\"]:1: invalid argument #1 to 'info' (function or level expected))")
print("!! [DETECTION] : FUNCTION HOOKED: game.GetService (Source: C:\\Users\\Administrator\\Documents\\nunu\\uveilr\\flow\\sandbox)")
print("!! [DETECTION] : FUNCTION HOOKED: debug.getinfo (Source: C:\\Users\\Administrator\\Documents\\nunu\\uveilr\\flow\\sandbox)")
print("!! [DETECTION] : FUNCTION HOOKED: require (Source: C:\\Users\\Administrator\\Documents\\nunu\\uveilr\\flow\\sandbox)")
print("!! [DETECTION] : FUNCTION HOOKED: getmetatable (Source: [C])")
print("!! [DETECTION] : FUNCTION HOOKED: setmetatable (Source: [C])")
print("!! [DETECTION] : FUNCTION HOOKED: error (Source: [C])")
print("!! [DETECTION] : FUNCTION HOOKED: pcall (Source: [C])")
local part = Instance.new("Part")
local _v1 = part:IsA("Part")
local _ = fenv.jX0aWqfjvX2i1G
print("!! [DETECTION] : CFrame Integrity Spoofed! (Got: CFrame.new(1, 1, 1))")
print("!! [DETECTION] : Color3 Integrity Spoofed! (Got: Color3.fromRGB(255, 255, 255))")
print("!! [DETECTION] : Vector3 Integrity Spoofed! (Got: Vector3.new(1, 2, 3))")
local _ = fenv.YgRr4gEgtV915q
print("!! [DETECTION] : External Debugger Accessing Upvalues")
local LogService = game:GetService("LogService")
local _ = fenv["0e3tN15Z2Rxik"]
print("!! [DETECTION] : Service Metatable Exposed: LogService")
local ScriptContext = game:GetService("ScriptContext")
print("!! [DETECTION] : Service Metatable Exposed: ScriptContext")
local Stats = game:GetService("Stats")
print("!! [DETECTION] : Service Metatable Exposed: Stats")
local RunService = game:GetService("RunService")
print("!! [DETECTION] : Service Metatable Exposed: RunService")
print("\n--- [ FULL PROTECTION REPORT ] ---")
print("[01] !! [DETECTION] : Executor Global Found: getgenv")
print("[02] !! [DETECTION] : Executor Global Found: getrenv")
print("[03] !! [DETECTION] : Executor Global Found: getreg")
print("[04] !! [DETECTION] : Executor Global Found: getrenv")
print("[05] !! [DETECTION] : Executor Global Found: getnilinstances")
print("[06] !! [DETECTION] : Executor Global Found: getgc")
print("[07] !! [DETECTION] : Executor Global Found: getconnections")
print("[08] !! [DETECTION] : Executor Global Found: getloadedmodules")
print("[09] !! [DETECTION] : Executor Global Found: hookfunction")
print("[10] !! [DETECTION] : Executor Global Found: hookmetamethod")
print("[11] !! [DETECTION] : Executor Global Found: replaceclosure")
print("[12] !! [DETECTION] : Executor Global Found: checkclosure")
print("[13] !! [DETECTION] : Executor Global Found: newcclosure")
print("[14] !! [DETECTION] : Executor Global Found: loadstring")
print("[15] !! [DETECTION] : Executor Global Found: getrawmetatable")
print("[16] !! [DETECTION] : Executor Global Found: setrawmetatable")
print("[17] !! [DETECTION] : Executor Global Found: setreadonly")
print("[18] !! [DETECTION] : Executor Global Found: isreadonly")
print("[19] !! [DETECTION] : Executor Global Found: isexecutorclosure")
print("[20] !! [DETECTION] : Executor Global Found: identifyexecutor")
print("[21] !! [DETECTION] : Executor Global Found: getexecutorname")
print("[22] !! [DETECTION] : FUNCTION HOOKED: xpcall (Source: [C])")
print("[23] !! [DETECTION] : FUNCTION HOOKED: warn (Source: C:\\Users\\Administrator\\Documents\\nunu\\uveilr\\flow\\sandbox)")
print("[24] !! [DETECTION] : FUNCTION HOOKED: rawset (Source: C:\\Users\\Administrator\\Documents\\nunu\\uveilr\\flow\\sandbox)")
print("[25] !! [DETECTION] : FUNCTION HOOKED: print (Source: C:\\Users\\Administrator\\Documents\\nunu\\uveilr\\flow\\sandbox)")
print("[26] !! [DETECTION] : FUNCTION HOOKED: debug.info (Source: [C])")
print("[27] !! [DETECTION] : FUNCTION HOOKED: game.HttpGet (Source: [string \"C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\tmp-8148-P6dUmAfzPA4T-.lua\"]:1: invalid argument #1 to 'info' (function or level expected))")
print("[28] !! [DETECTION] : FUNCTION HOOKED: game.GetService (Source: C:\\Users\\Administrator\\Documents\\nunu\\uveilr\\flow\\sandbox)")
print("[29] !! [DETECTION] : FUNCTION HOOKED: debug.getinfo (Source: C:\\Users\\Administrator\\Documents\\nunu\\uveilr\\flow\\sandbox)")
print("[30] !! [DETECTION] : FUNCTION HOOKED: require (Source: C:\\Users\\Administrator\\Documents\\nunu\\uveilr\\flow\\sandbox)")
print("[31] !! [DETECTION] : FUNCTION HOOKED: getmetatable (Source: [C])")
print("[32] !! [DETECTION] : FUNCTION HOOKED: setmetatable (Source: [C])")
print("[33] !! [DETECTION] : FUNCTION HOOKED: error (Source: [C])")
print("[34] !! [DETECTION] : FUNCTION HOOKED: pcall (Source: [C])")
print("[35] !! [DETECTION] : CFrame Integrity Spoofed! (Got: CFrame.new(1, 1, 1))")
print("[36] !! [DETECTION] : Color3 Integrity Spoofed! (Got: Color3.fromRGB(255, 255, 255))")
print("[37] !! [DETECTION] : Vector3 Integrity Spoofed! (Got: Vector3.new(1, 2, 3))")
print("[38] !! [DETECTION] : External Debugger Accessing Upvalues")
print("[39] !! [DETECTION] : Service Metatable Exposed: LogService")
print("[40] !! [DETECTION] : Service Metatable Exposed: ScriptContext")
print("[41] !! [DETECTION] : Service Metatable Exposed: Stats")
print("[42] !! [DETECTION] : Service Metatable Exposed: RunService")
local _ = fenv.AN1gN3i4J9BQ
print("----------------------------------\n")